### ISSUE TITLE
[Compile] ‘hex’ is not a member of ‘Qt’

### ISSUE THREAD

**Issue by telanus** [86Box/86Box#3255]
**Describe the bug**
When compiling https://github.com/86Box/86Box/commit/7bc213a9544c9d9018fa22e58f81200819d76e3c it error out with the above error

**To Reproduce**
Compile on Ubuntu 20.04

**Expected behavior**
It compiles perfectly

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04
 - QT: 5.12.8
 - Build information: GCC 11.1.0

**Additional context**
```
[ 81%] Building CXX object src/qt/CMakeFiles/ui.dir/xkbcommon_keyboard.cpp.o
~/src/86Box1/src/qt/xkbcommon_keyboard.cpp: In function ‘uint16_t xkbcommon_translate(uint32_t)’:
~/src/86Box1/src/qt/xkbcommon_keyboard.cpp:227:58: error: ‘hex’ is not a member of ‘Qt’
  227 |         qWarning() << "XKB Keyboard: Unknown key" << Qt::hex << keycode << QString::fromStdString(key_name_s);
      |                                                          ^~~
~/src/86Box1/src/qt/xkbcommon_keyboard.cpp:227:58: note: suggested alternatives:
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QtDebug:1,
                 from ~/src/86Box1/src/qt/xkbcommon_keyboard.cpp:22:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h:239:28: note:   ‘hex’
  239 | Q_CORE_EXPORT QTextStream &hex(QTextStream &s);
      |                            ^~~
In file included from /usr/include/c++/11/streambuf:41,
                 from /usr/include/c++/11/bits/streambuf_iterator.h:35,
                 from /usr/include/c++/11/iterator:66,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qbytearray.h:53,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:49,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qhashfunctions.h:44,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:47,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qhash.h:46,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QtDebug:1,
                 from ~/src/86Box1/src/qt/xkbcommon_keyboard.cpp:22:
/usr/include/c++/11/bits/ios_base.h:1054:3: note:   ‘std::hex’
 1054 |   hex(ios_base& __base)
      |   ^~~
make[2]: *** [src/qt/CMakeFiles/ui.dir/build.make:853: src/qt/CMakeFiles/ui.dir/xkbcommon_keyboard.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1292: src/qt/CMakeFiles/ui.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by cold-brewed** [comment]
Note: The `Qt::hex` error is unrelated to the linked commit. It appears to have been in the file (`xkbcommon_keyboard.cpp`) since it was first introduced (prior to the linked commit).

**Comment by richardg867** [comment]
Fixed by 0125d14
