### ISSUE TITLE
Fails to build with Qt 6.10

### ISSUE THREAD

**Issue by xiota** [86Box/86Box#6326]
### Checklist

- [x] I **have searched** the issue tracker and **was unable** to find an [open](../issues?q=is%3Aissue+is%3Aopen) or [closed](../issues?q=is%3Aissue+is%3Aclosed) issue matching what I'm seeing.
- [x] I **have verified** that the issue is happening in the **[latest nightly build](https://ci.86box.net/job/86Box/lastSuccessfulBuild/artifact/)**, or the latest commit, if building from source.

### What happened?

Fails to build with Qt 6.10 because access to private components was changed.  Needs changes to cmake scripts. 
```
/home/builder/build/src/86box-git/src/qt/qt_mainwindow.cpp:127:10: fatal error: qpa/qplatformwindow.h: No such file or directory
  127 | #include <qpa/qplatformwindow.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Configuration file

```ini
N/A
```

### Operating system

Arch Linux

### 86Box version

74678a391b8806661b18a7fd9251b26d3b887fc0

### Build architecture

Linux - x64 (64-bit)

### Build type

- [ ] New recompiler
- [ ] Debug build

### Additional context

Error occurs during build, so runtime info not relevant.

**Comment by jriwanek** [comment]
And what's the new location?

**Comment by xiota** [comment]
Location of the header is the same.  But need to add something like `find_package(Qt6 COMPONENTS GuiPrivate)` and `target_link_libraries(xyz PRIVATE Qt::GuiPrivate)` for it to be available and link properly.
